//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.0
//     from Assets/15.Input System/PlayerInputAction.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputAction"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""3c7f644c-1ae3-4f23-a88a-cc4eeb85255a"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""a9cc1f3e-7dbc-4db8-a0b0-20ff6020f891"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""ZoomCamara"",
                    ""type"": ""Value"",
                    ""id"": ""6194913c-ae53-4a6e-8681-118f17d7b5b0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""RotateCamera"",
                    ""type"": ""Value"",
                    ""id"": ""0c8d79af-fbb9-4a83-84f8-dd44f71b74b3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""0a940c08-bbd1-4735-a607-994d8592c0d0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""BasicAttack"",
                    ""type"": ""Button"",
                    ""id"": ""bb53f2fa-4217-4e80-8f77-7f519040d91b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Shield"",
                    ""type"": ""Button"",
                    ""id"": ""bdf85e5e-ecd4-4fe3-adfc-a6c37c853951"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Sneak"",
                    ""type"": ""Button"",
                    ""id"": ""c7139ecc-32c2-40f9-b07c-89ed925de665"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Running"",
                    ""type"": ""Button"",
                    ""id"": ""aeea85b1-1cc6-45c6-ad13-d24c3eb7d79c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold""
                },
                {
                    ""name"": ""Roll"",
                    ""type"": ""Button"",
                    ""id"": ""d3df30ae-a747-40da-bf4c-a3deb9d016ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey1"",
                    ""type"": ""Button"",
                    ""id"": ""290287df-b9d4-4a00-8399-7333b647c16b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey2"",
                    ""type"": ""Button"",
                    ""id"": ""4ae2fdb2-6a60-4dbb-a308-22faf9897951"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey3"",
                    ""type"": ""Button"",
                    ""id"": ""03642da3-7025-4a9f-8972-4f1f85af8356"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey4"",
                    ""type"": ""Button"",
                    ""id"": ""98140934-0af5-47d9-9fde-5a107f1e56c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey5"",
                    ""type"": ""Button"",
                    ""id"": ""2165332d-0cf2-4777-90cd-25e10d737f70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey6"",
                    ""type"": ""Button"",
                    ""id"": ""dc2a1011-39ef-4191-8a3e-f8945c7e720a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey7"",
                    ""type"": ""Button"",
                    ""id"": ""87268a7b-a705-409b-b58e-0857822914ea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey8"",
                    ""type"": ""Button"",
                    ""id"": ""5e97acf6-37ac-40be-b3ba-6ecf0cf8ab2a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey9"",
                    ""type"": ""Button"",
                    ""id"": ""70fd7e67-9526-4d28-b759-8d603d2e6472"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""SkillHotKey0"",
                    ""type"": ""Button"",
                    ""id"": ""94aad59f-1726-404f-bfad-bcfed4aa8f59"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.3)""
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d714b40f-d38c-49ee-8ca6-d522e5f44c42"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""8c571e9d-5bb5-4d1f-95e9-bf4721abc770"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""71ae4355-33ab-46dc-9273-82564d6d0f88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""012c0bb3-4c75-4a9b-acae-9e77ad509bdd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""Value"",
                    ""id"": ""feacb067-fbf5-4d66-8932-30d01cf198d6"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""Button"",
                    ""id"": ""240517a6-49ac-407d-be66-6e676157b0e6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""7376905f-5e20-4c7c-a5ff-af9abe5a7c61"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5fb69923-d7b2-4939-8d22-943dc99015f2"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d6d82e4c-2993-496e-9929-e140a6681ff4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""1889e2d4-7cc4-47e1-9eeb-072f29612bc5"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""75f3e559-72d7-4c5e-bbc5-147c675e537b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""05388a0d-9163-47d5-9e98-1d2442b3e9d7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Arrows"",
                    ""id"": ""f515e9c5-1f21-4223-a722-3cb99250e697"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e9d39010-0014-4886-aec1-a1d039e5b52a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""4d1afa80-9c75-43ed-b418-aca24293425d"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""eae036c6-feaa-430d-b169-65c4f4b92f95"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""0a8ccce4-a153-48bd-8789-b02ce0a3be70"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""3e32846b-d65a-4256-87ae-208dcaaf5bf4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e308a92-95f9-487c-a481-a248ce3f0e92"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""76f4e090-31d5-481a-813a-408b8034758a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4095a5d-8c50-42a2-96ba-58818a9e97e2"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""BasicAttack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""933626f6-d584-41b6-9f41-6f2c88d1b447"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c0244da-b0a9-4219-9dca-389486fa01ec"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Shield"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d0be7fff-a1da-4cfa-911f-3b88ffba6d20"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Sneak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bc61a50a-a004-44ac-b890-0c46c6b8dcf3"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Sneak"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e12e31d4-2ff3-4705-9390-12070ccac07c"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Running"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""22d94372-63b5-4b67-a32c-5fcc746a5ecf"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""518b1d15-a47c-4072-b8bf-4bf9d89a5ff8"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Roll"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0ca75779-7e69-43f2-80a8-88462761876d"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""ZoomCamara"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4157e6a9-7e13-4345-ba0b-0d3aac97ef4a"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ee4a99-345c-4736-9d72-a72cd830bec3"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=10,y=10)"",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RotateCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac5564c2-089e-451b-bb6f-d8dba5968225"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7c97b499-93a1-49d6-baf3-8075c4837b63"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SkillHotKey1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac66fda6-ecdc-45e8-9321-201dfbddb964"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5ec9150-426f-4221-8b90-2af567123e5d"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""SkillHotKey2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165bde87-cfb6-4e5e-b29f-cd0cb263c0a1"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""347aa3df-1985-42d5-93c6-4db43ce27bf8"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillHotKey3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09107735-85de-41b9-9948-0c0190b55aba"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad0c260e-d6d4-4c26-ba50-96701db9da3c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SkillHotKey4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb6f6813-b5c6-4298-8321-31704a6232da"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1e58801-43d5-438d-beb5-af27bf606cac"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77181b5e-6168-4fb4-b32e-a995d988c78d"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4758d45-df8c-4b1c-b15d-156a67e64c7b"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c9ae1211-0b80-451a-a275-cb6056c24599"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfabc63e-79d4-4884-a60f-78f81c046681"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""SkillHotKey0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a536baea-cc15-4f5a-922c-04efd316b4bf"",
                    ""path"": ""<VirtualMouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c5bbe74-bdd9-42f0-be4d-0015147f8875"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aba0846f-5e80-4251-bfb7-186559a6847e"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cda5f5cc-1791-4a05-b558-0a6a6b11857c"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cfd6b57-5ec4-45aa-98f1-b3f415a8cbc2"",
                    ""path"": ""<VirtualMouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c578d39c-c9ed-477a-bd00-f292abdc0df3"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8c0979b-9c91-4190-9fd1-67af97f71084"",
                    ""path"": ""<VirtualMouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""77ea763c-e938-43be-aae4-4cb79c2c10d9"",
                    ""path"": ""<VirtualMouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8ef665b-b31d-4b74-aea5-5ffee58e4db7"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""2fa638ba-7049-4a70-82f2-d5c777b99242"",
            ""actions"": [
                {
                    ""name"": ""Inventory"",
                    ""type"": ""Button"",
                    ""id"": ""43dee940-d98d-4e25-9aa9-8541b20eb20f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Skill"",
                    ""type"": ""Button"",
                    ""id"": ""66a5e940-7f85-46ef-812e-9dfafd89bbe9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Artifact"",
                    ""type"": ""Button"",
                    ""id"": ""9a677985-de7a-4e67-af7c-0d6c7e8e2840"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Map"",
                    ""type"": ""Button"",
                    ""id"": ""58e1af40-336e-409e-9b60-f2eee3eef6f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Consloe"",
                    ""type"": ""Button"",
                    ""id"": ""cb638d79-c411-412c-b840-ab26c46f9a58"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""Minimap"",
                    ""type"": ""Button"",
                    ""id"": ""7860b503-bc74-4aa7-85b6-dbf269385285"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MinimapZoomIn"",
                    ""type"": ""Button"",
                    ""id"": ""afd74f59-8941-4806-83a0-75bdcd291596"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""MinimapZoomOut1"",
                    ""type"": ""Button"",
                    ""id"": ""e93db581-3821-4e6c-a5a9-e557d823220e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""QuickUseFirstSlot"",
                    ""type"": ""Button"",
                    ""id"": ""b9eff460-5337-4269-b764-b11465e08890"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.5)""
                },
                {
                    ""name"": ""QuickUseFirstHold"",
                    ""type"": ""Button"",
                    ""id"": ""1aa871f2-486d-4a99-82ea-13fd7277cc0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.5)""
                },
                {
                    ""name"": ""QuickUseSecondSlot"",
                    ""type"": ""Button"",
                    ""id"": ""a2586112-45bc-4913-a563-dd6a34db368b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap(duration=0.5)""
                },
                {
                    ""name"": ""QuickUseSecondHold"",
                    ""type"": ""Button"",
                    ""id"": ""6aded6d5-8489-4b6d-aa56-0b99afe9f2ee"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold(duration=0.5)""
                },
                {
                    ""name"": ""EscMenu"",
                    ""type"": ""Button"",
                    ""id"": ""42ba2de4-a7b2-46ff-b682-d576a321ae84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""PickUp"",
                    ""type"": ""Button"",
                    ""id"": ""9e8d1c20-9af8-4357-8929-f798ec71c12c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                },
                {
                    ""name"": ""UI"",
                    ""type"": ""Button"",
                    ""id"": ""a0e6d803-6c8b-4a18-860f-076faf41c119"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """"
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4b2e4b99-fb86-4589-b7b9-2aecb4929736"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7448c84-2248-43f8-8621-b83e779af7a1"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Skill"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be710230-cc23-44cf-b73f-c7b652768259"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Consloe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6d2145d-2249-4960-a308-533fdc9bfe20"",
                    ""path"": ""<Keyboard>/rightBracket"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Minimap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41fc954e-28a8-4d81-b054-6fccae170f34"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""QuickUseFirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""455197e6-5ed0-405d-8f98-268f33407e71"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""QuickUseFirstSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5af8f0f9-bc8f-452f-9544-6f4ef8c03a45"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""QuickUseSecondSlot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6e1bfe8-492d-46d1-a877-8783db2a5355"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ee8ef4e3-84bf-4f42-a793-f0e50fce25a5"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Inventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""971c69f8-f490-4088-962b-4949bbb3e94d"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""EscMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cff8147-71dc-4e35-8e2d-d8c6006b6dc1"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""EscMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0abc70d9-e835-4d08-a989-629d6f9b47da"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4ba4e77-2c5c-47df-9fd9-1f3fc318cbcb"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""PickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a86ea974-827b-4678-8d5e-6d90d3b100b8"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""QuickUseSecondHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb0c909e-a307-4223-a81c-431fb3df72ee"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""QuickUseFirstHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc465770-860c-461b-b8a4-22a4f5d2f7ce"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""QuickUseFirstHold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""481b3208-f1fc-4e49-9e8e-d6820159de42"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MinimapZoomIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6b534dc-bd6b-4ab9-9bef-b6d48e38cee7"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""MinimapZoomOut1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3f4e5ce-eb08-49d4-8dde-ca8a482b3974"",
                    ""path"": ""<Keyboard>/f11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""UI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cb993f28-abfa-4a59-a36a-cf35ebb4bd12"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Artifact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fe6c57c-46b9-4b9c-86e9-d473131988e2"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Artifact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""809a940f-8e1c-48f6-b1ea-2c01e01cc38d"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""520fb8d9-1108-4255-9b81-39998df036dc"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Gamepad"",
                    ""action"": ""Map"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_ZoomCamara = m_Player.FindAction("ZoomCamara", throwIfNotFound: true);
        m_Player_RotateCamera = m_Player.FindAction("RotateCamera", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_BasicAttack = m_Player.FindAction("BasicAttack", throwIfNotFound: true);
        m_Player_Shield = m_Player.FindAction("Shield", throwIfNotFound: true);
        m_Player_Sneak = m_Player.FindAction("Sneak", throwIfNotFound: true);
        m_Player_Running = m_Player.FindAction("Running", throwIfNotFound: true);
        m_Player_Roll = m_Player.FindAction("Roll", throwIfNotFound: true);
        m_Player_SkillHotKey1 = m_Player.FindAction("SkillHotKey1", throwIfNotFound: true);
        m_Player_SkillHotKey2 = m_Player.FindAction("SkillHotKey2", throwIfNotFound: true);
        m_Player_SkillHotKey3 = m_Player.FindAction("SkillHotKey3", throwIfNotFound: true);
        m_Player_SkillHotKey4 = m_Player.FindAction("SkillHotKey4", throwIfNotFound: true);
        m_Player_SkillHotKey5 = m_Player.FindAction("SkillHotKey5", throwIfNotFound: true);
        m_Player_SkillHotKey6 = m_Player.FindAction("SkillHotKey6", throwIfNotFound: true);
        m_Player_SkillHotKey7 = m_Player.FindAction("SkillHotKey7", throwIfNotFound: true);
        m_Player_SkillHotKey8 = m_Player.FindAction("SkillHotKey8", throwIfNotFound: true);
        m_Player_SkillHotKey9 = m_Player.FindAction("SkillHotKey9", throwIfNotFound: true);
        m_Player_SkillHotKey0 = m_Player.FindAction("SkillHotKey0", throwIfNotFound: true);
        m_Player_Point = m_Player.FindAction("Point", throwIfNotFound: true);
        m_Player_Submit = m_Player.FindAction("Submit", throwIfNotFound: true);
        m_Player_Cancel = m_Player.FindAction("Cancel", throwIfNotFound: true);
        m_Player_Click = m_Player.FindAction("Click", throwIfNotFound: true);
        m_Player_ScrollWheel = m_Player.FindAction("ScrollWheel", throwIfNotFound: true);
        m_Player_RightClick = m_Player.FindAction("RightClick", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Inventory = m_UI.FindAction("Inventory", throwIfNotFound: true);
        m_UI_Skill = m_UI.FindAction("Skill", throwIfNotFound: true);
        m_UI_Artifact = m_UI.FindAction("Artifact", throwIfNotFound: true);
        m_UI_Map = m_UI.FindAction("Map", throwIfNotFound: true);
        m_UI_Consloe = m_UI.FindAction("Consloe", throwIfNotFound: true);
        m_UI_Minimap = m_UI.FindAction("Minimap", throwIfNotFound: true);
        m_UI_MinimapZoomIn = m_UI.FindAction("MinimapZoomIn", throwIfNotFound: true);
        m_UI_MinimapZoomOut1 = m_UI.FindAction("MinimapZoomOut1", throwIfNotFound: true);
        m_UI_QuickUseFirstSlot = m_UI.FindAction("QuickUseFirstSlot", throwIfNotFound: true);
        m_UI_QuickUseFirstHold = m_UI.FindAction("QuickUseFirstHold", throwIfNotFound: true);
        m_UI_QuickUseSecondSlot = m_UI.FindAction("QuickUseSecondSlot", throwIfNotFound: true);
        m_UI_QuickUseSecondHold = m_UI.FindAction("QuickUseSecondHold", throwIfNotFound: true);
        m_UI_EscMenu = m_UI.FindAction("EscMenu", throwIfNotFound: true);
        m_UI_PickUp = m_UI.FindAction("PickUp", throwIfNotFound: true);
        m_UI_UI = m_UI.FindAction("UI", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_ZoomCamara;
    private readonly InputAction m_Player_RotateCamera;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_BasicAttack;
    private readonly InputAction m_Player_Shield;
    private readonly InputAction m_Player_Sneak;
    private readonly InputAction m_Player_Running;
    private readonly InputAction m_Player_Roll;
    private readonly InputAction m_Player_SkillHotKey1;
    private readonly InputAction m_Player_SkillHotKey2;
    private readonly InputAction m_Player_SkillHotKey3;
    private readonly InputAction m_Player_SkillHotKey4;
    private readonly InputAction m_Player_SkillHotKey5;
    private readonly InputAction m_Player_SkillHotKey6;
    private readonly InputAction m_Player_SkillHotKey7;
    private readonly InputAction m_Player_SkillHotKey8;
    private readonly InputAction m_Player_SkillHotKey9;
    private readonly InputAction m_Player_SkillHotKey0;
    private readonly InputAction m_Player_Point;
    private readonly InputAction m_Player_Submit;
    private readonly InputAction m_Player_Cancel;
    private readonly InputAction m_Player_Click;
    private readonly InputAction m_Player_ScrollWheel;
    private readonly InputAction m_Player_RightClick;
    public struct PlayerActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @ZoomCamara => m_Wrapper.m_Player_ZoomCamara;
        public InputAction @RotateCamera => m_Wrapper.m_Player_RotateCamera;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @BasicAttack => m_Wrapper.m_Player_BasicAttack;
        public InputAction @Shield => m_Wrapper.m_Player_Shield;
        public InputAction @Sneak => m_Wrapper.m_Player_Sneak;
        public InputAction @Running => m_Wrapper.m_Player_Running;
        public InputAction @Roll => m_Wrapper.m_Player_Roll;
        public InputAction @SkillHotKey1 => m_Wrapper.m_Player_SkillHotKey1;
        public InputAction @SkillHotKey2 => m_Wrapper.m_Player_SkillHotKey2;
        public InputAction @SkillHotKey3 => m_Wrapper.m_Player_SkillHotKey3;
        public InputAction @SkillHotKey4 => m_Wrapper.m_Player_SkillHotKey4;
        public InputAction @SkillHotKey5 => m_Wrapper.m_Player_SkillHotKey5;
        public InputAction @SkillHotKey6 => m_Wrapper.m_Player_SkillHotKey6;
        public InputAction @SkillHotKey7 => m_Wrapper.m_Player_SkillHotKey7;
        public InputAction @SkillHotKey8 => m_Wrapper.m_Player_SkillHotKey8;
        public InputAction @SkillHotKey9 => m_Wrapper.m_Player_SkillHotKey9;
        public InputAction @SkillHotKey0 => m_Wrapper.m_Player_SkillHotKey0;
        public InputAction @Point => m_Wrapper.m_Player_Point;
        public InputAction @Submit => m_Wrapper.m_Player_Submit;
        public InputAction @Cancel => m_Wrapper.m_Player_Cancel;
        public InputAction @Click => m_Wrapper.m_Player_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_Player_ScrollWheel;
        public InputAction @RightClick => m_Wrapper.m_Player_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMove;
                @ZoomCamara.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoomCamara;
                @ZoomCamara.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoomCamara;
                @ZoomCamara.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnZoomCamara;
                @RotateCamera.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCamera;
                @RotateCamera.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRotateCamera;
                @Jump.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnJump;
                @BasicAttack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttack;
                @BasicAttack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBasicAttack;
                @Shield.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Shield.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Shield.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShield;
                @Sneak.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSneak;
                @Sneak.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSneak;
                @Sneak.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSneak;
                @Running.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Running.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Running.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRunning;
                @Roll.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @Roll.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @Roll.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRoll;
                @SkillHotKey1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey1;
                @SkillHotKey1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey1;
                @SkillHotKey1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey1;
                @SkillHotKey2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey2;
                @SkillHotKey2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey2;
                @SkillHotKey2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey2;
                @SkillHotKey3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey3;
                @SkillHotKey3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey3;
                @SkillHotKey3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey3;
                @SkillHotKey4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey4;
                @SkillHotKey4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey4;
                @SkillHotKey4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey4;
                @SkillHotKey5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey5;
                @SkillHotKey5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey5;
                @SkillHotKey5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey5;
                @SkillHotKey6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey6;
                @SkillHotKey6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey6;
                @SkillHotKey6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey6;
                @SkillHotKey7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey7;
                @SkillHotKey7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey7;
                @SkillHotKey7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey7;
                @SkillHotKey8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey8;
                @SkillHotKey8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey8;
                @SkillHotKey8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey8;
                @SkillHotKey9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey9;
                @SkillHotKey9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey9;
                @SkillHotKey9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey9;
                @SkillHotKey0.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey0;
                @SkillHotKey0.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey0;
                @SkillHotKey0.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSkillHotKey0;
                @Point.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPoint;
                @Submit.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnCancel;
                @Click.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnScrollWheel;
                @RightClick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnRightClick;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @ZoomCamara.started += instance.OnZoomCamara;
                @ZoomCamara.performed += instance.OnZoomCamara;
                @ZoomCamara.canceled += instance.OnZoomCamara;
                @RotateCamera.started += instance.OnRotateCamera;
                @RotateCamera.performed += instance.OnRotateCamera;
                @RotateCamera.canceled += instance.OnRotateCamera;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @BasicAttack.started += instance.OnBasicAttack;
                @BasicAttack.performed += instance.OnBasicAttack;
                @BasicAttack.canceled += instance.OnBasicAttack;
                @Shield.started += instance.OnShield;
                @Shield.performed += instance.OnShield;
                @Shield.canceled += instance.OnShield;
                @Sneak.started += instance.OnSneak;
                @Sneak.performed += instance.OnSneak;
                @Sneak.canceled += instance.OnSneak;
                @Running.started += instance.OnRunning;
                @Running.performed += instance.OnRunning;
                @Running.canceled += instance.OnRunning;
                @Roll.started += instance.OnRoll;
                @Roll.performed += instance.OnRoll;
                @Roll.canceled += instance.OnRoll;
                @SkillHotKey1.started += instance.OnSkillHotKey1;
                @SkillHotKey1.performed += instance.OnSkillHotKey1;
                @SkillHotKey1.canceled += instance.OnSkillHotKey1;
                @SkillHotKey2.started += instance.OnSkillHotKey2;
                @SkillHotKey2.performed += instance.OnSkillHotKey2;
                @SkillHotKey2.canceled += instance.OnSkillHotKey2;
                @SkillHotKey3.started += instance.OnSkillHotKey3;
                @SkillHotKey3.performed += instance.OnSkillHotKey3;
                @SkillHotKey3.canceled += instance.OnSkillHotKey3;
                @SkillHotKey4.started += instance.OnSkillHotKey4;
                @SkillHotKey4.performed += instance.OnSkillHotKey4;
                @SkillHotKey4.canceled += instance.OnSkillHotKey4;
                @SkillHotKey5.started += instance.OnSkillHotKey5;
                @SkillHotKey5.performed += instance.OnSkillHotKey5;
                @SkillHotKey5.canceled += instance.OnSkillHotKey5;
                @SkillHotKey6.started += instance.OnSkillHotKey6;
                @SkillHotKey6.performed += instance.OnSkillHotKey6;
                @SkillHotKey6.canceled += instance.OnSkillHotKey6;
                @SkillHotKey7.started += instance.OnSkillHotKey7;
                @SkillHotKey7.performed += instance.OnSkillHotKey7;
                @SkillHotKey7.canceled += instance.OnSkillHotKey7;
                @SkillHotKey8.started += instance.OnSkillHotKey8;
                @SkillHotKey8.performed += instance.OnSkillHotKey8;
                @SkillHotKey8.canceled += instance.OnSkillHotKey8;
                @SkillHotKey9.started += instance.OnSkillHotKey9;
                @SkillHotKey9.performed += instance.OnSkillHotKey9;
                @SkillHotKey9.canceled += instance.OnSkillHotKey9;
                @SkillHotKey0.started += instance.OnSkillHotKey0;
                @SkillHotKey0.performed += instance.OnSkillHotKey0;
                @SkillHotKey0.canceled += instance.OnSkillHotKey0;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Inventory;
    private readonly InputAction m_UI_Skill;
    private readonly InputAction m_UI_Artifact;
    private readonly InputAction m_UI_Map;
    private readonly InputAction m_UI_Consloe;
    private readonly InputAction m_UI_Minimap;
    private readonly InputAction m_UI_MinimapZoomIn;
    private readonly InputAction m_UI_MinimapZoomOut1;
    private readonly InputAction m_UI_QuickUseFirstSlot;
    private readonly InputAction m_UI_QuickUseFirstHold;
    private readonly InputAction m_UI_QuickUseSecondSlot;
    private readonly InputAction m_UI_QuickUseSecondHold;
    private readonly InputAction m_UI_EscMenu;
    private readonly InputAction m_UI_PickUp;
    private readonly InputAction m_UI_UI;
    public struct UIActions
    {
        private @PlayerInputAction m_Wrapper;
        public UIActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Inventory => m_Wrapper.m_UI_Inventory;
        public InputAction @Skill => m_Wrapper.m_UI_Skill;
        public InputAction @Artifact => m_Wrapper.m_UI_Artifact;
        public InputAction @Map => m_Wrapper.m_UI_Map;
        public InputAction @Consloe => m_Wrapper.m_UI_Consloe;
        public InputAction @Minimap => m_Wrapper.m_UI_Minimap;
        public InputAction @MinimapZoomIn => m_Wrapper.m_UI_MinimapZoomIn;
        public InputAction @MinimapZoomOut1 => m_Wrapper.m_UI_MinimapZoomOut1;
        public InputAction @QuickUseFirstSlot => m_Wrapper.m_UI_QuickUseFirstSlot;
        public InputAction @QuickUseFirstHold => m_Wrapper.m_UI_QuickUseFirstHold;
        public InputAction @QuickUseSecondSlot => m_Wrapper.m_UI_QuickUseSecondSlot;
        public InputAction @QuickUseSecondHold => m_Wrapper.m_UI_QuickUseSecondHold;
        public InputAction @EscMenu => m_Wrapper.m_UI_EscMenu;
        public InputAction @PickUp => m_Wrapper.m_UI_PickUp;
        public InputAction @UI => m_Wrapper.m_UI_UI;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Inventory.started -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Inventory.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Inventory.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnInventory;
                @Skill.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSkill;
                @Skill.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSkill;
                @Skill.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSkill;
                @Artifact.started -= m_Wrapper.m_UIActionsCallbackInterface.OnArtifact;
                @Artifact.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnArtifact;
                @Artifact.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnArtifact;
                @Map.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMap;
                @Map.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMap;
                @Map.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMap;
                @Consloe.started -= m_Wrapper.m_UIActionsCallbackInterface.OnConsloe;
                @Consloe.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnConsloe;
                @Consloe.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnConsloe;
                @Minimap.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @Minimap.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @Minimap.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimap;
                @MinimapZoomIn.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomIn;
                @MinimapZoomIn.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomIn;
                @MinimapZoomIn.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomIn;
                @MinimapZoomOut1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomOut1;
                @MinimapZoomOut1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomOut1;
                @MinimapZoomOut1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMinimapZoomOut1;
                @QuickUseFirstSlot.started -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstSlot;
                @QuickUseFirstSlot.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstSlot;
                @QuickUseFirstSlot.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstSlot;
                @QuickUseFirstHold.started -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstHold;
                @QuickUseFirstHold.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstHold;
                @QuickUseFirstHold.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseFirstHold;
                @QuickUseSecondSlot.started -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondSlot;
                @QuickUseSecondSlot.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondSlot;
                @QuickUseSecondSlot.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondSlot;
                @QuickUseSecondHold.started -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondHold;
                @QuickUseSecondHold.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondHold;
                @QuickUseSecondHold.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnQuickUseSecondHold;
                @EscMenu.started -= m_Wrapper.m_UIActionsCallbackInterface.OnEscMenu;
                @EscMenu.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnEscMenu;
                @EscMenu.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnEscMenu;
                @PickUp.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPickUp;
                @PickUp.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPickUp;
                @PickUp.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPickUp;
                @UI.started -= m_Wrapper.m_UIActionsCallbackInterface.OnUI;
                @UI.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnUI;
                @UI.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnUI;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Inventory.started += instance.OnInventory;
                @Inventory.performed += instance.OnInventory;
                @Inventory.canceled += instance.OnInventory;
                @Skill.started += instance.OnSkill;
                @Skill.performed += instance.OnSkill;
                @Skill.canceled += instance.OnSkill;
                @Artifact.started += instance.OnArtifact;
                @Artifact.performed += instance.OnArtifact;
                @Artifact.canceled += instance.OnArtifact;
                @Map.started += instance.OnMap;
                @Map.performed += instance.OnMap;
                @Map.canceled += instance.OnMap;
                @Consloe.started += instance.OnConsloe;
                @Consloe.performed += instance.OnConsloe;
                @Consloe.canceled += instance.OnConsloe;
                @Minimap.started += instance.OnMinimap;
                @Minimap.performed += instance.OnMinimap;
                @Minimap.canceled += instance.OnMinimap;
                @MinimapZoomIn.started += instance.OnMinimapZoomIn;
                @MinimapZoomIn.performed += instance.OnMinimapZoomIn;
                @MinimapZoomIn.canceled += instance.OnMinimapZoomIn;
                @MinimapZoomOut1.started += instance.OnMinimapZoomOut1;
                @MinimapZoomOut1.performed += instance.OnMinimapZoomOut1;
                @MinimapZoomOut1.canceled += instance.OnMinimapZoomOut1;
                @QuickUseFirstSlot.started += instance.OnQuickUseFirstSlot;
                @QuickUseFirstSlot.performed += instance.OnQuickUseFirstSlot;
                @QuickUseFirstSlot.canceled += instance.OnQuickUseFirstSlot;
                @QuickUseFirstHold.started += instance.OnQuickUseFirstHold;
                @QuickUseFirstHold.performed += instance.OnQuickUseFirstHold;
                @QuickUseFirstHold.canceled += instance.OnQuickUseFirstHold;
                @QuickUseSecondSlot.started += instance.OnQuickUseSecondSlot;
                @QuickUseSecondSlot.performed += instance.OnQuickUseSecondSlot;
                @QuickUseSecondSlot.canceled += instance.OnQuickUseSecondSlot;
                @QuickUseSecondHold.started += instance.OnQuickUseSecondHold;
                @QuickUseSecondHold.performed += instance.OnQuickUseSecondHold;
                @QuickUseSecondHold.canceled += instance.OnQuickUseSecondHold;
                @EscMenu.started += instance.OnEscMenu;
                @EscMenu.performed += instance.OnEscMenu;
                @EscMenu.canceled += instance.OnEscMenu;
                @PickUp.started += instance.OnPickUp;
                @PickUp.performed += instance.OnPickUp;
                @PickUp.canceled += instance.OnPickUp;
                @UI.started += instance.OnUI;
                @UI.performed += instance.OnUI;
                @UI.canceled += instance.OnUI;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnZoomCamara(InputAction.CallbackContext context);
        void OnRotateCamera(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnBasicAttack(InputAction.CallbackContext context);
        void OnShield(InputAction.CallbackContext context);
        void OnSneak(InputAction.CallbackContext context);
        void OnRunning(InputAction.CallbackContext context);
        void OnRoll(InputAction.CallbackContext context);
        void OnSkillHotKey1(InputAction.CallbackContext context);
        void OnSkillHotKey2(InputAction.CallbackContext context);
        void OnSkillHotKey3(InputAction.CallbackContext context);
        void OnSkillHotKey4(InputAction.CallbackContext context);
        void OnSkillHotKey5(InputAction.CallbackContext context);
        void OnSkillHotKey6(InputAction.CallbackContext context);
        void OnSkillHotKey7(InputAction.CallbackContext context);
        void OnSkillHotKey8(InputAction.CallbackContext context);
        void OnSkillHotKey9(InputAction.CallbackContext context);
        void OnSkillHotKey0(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnInventory(InputAction.CallbackContext context);
        void OnSkill(InputAction.CallbackContext context);
        void OnArtifact(InputAction.CallbackContext context);
        void OnMap(InputAction.CallbackContext context);
        void OnConsloe(InputAction.CallbackContext context);
        void OnMinimap(InputAction.CallbackContext context);
        void OnMinimapZoomIn(InputAction.CallbackContext context);
        void OnMinimapZoomOut1(InputAction.CallbackContext context);
        void OnQuickUseFirstSlot(InputAction.CallbackContext context);
        void OnQuickUseFirstHold(InputAction.CallbackContext context);
        void OnQuickUseSecondSlot(InputAction.CallbackContext context);
        void OnQuickUseSecondHold(InputAction.CallbackContext context);
        void OnEscMenu(InputAction.CallbackContext context);
        void OnPickUp(InputAction.CallbackContext context);
        void OnUI(InputAction.CallbackContext context);
    }
}
